name: Clean Up Dry Runs

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

jobs:
  clean-up:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - DEV_ENV
          - PROD_ENV
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.x

      - name: Setup Environment Variables
        run: echo '${{ secrets[matrix.env] }}' > .env

      - name: Setup Google Credentials
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Setup Google OAuth
        run: echo '${{ secrets.GOOGLE_OAUTH }}' > oauth-token.json

      - name: Install Dependencies
        run: npm ci

      - name: Clean Up Stale Dry Runs
        run: npm run clean-up-stale-dry-runs
